import { cp, mkdir, writeFile } from "node:fs/promises";

// htmx (existing behaviour)
await mkdir("static/js", { recursive: true });
await cp("node_modules/htmx.org/dist/htmx.esm.min.js", "static/js/htmx.esm.min.js");

// @mdi/js icons -> generated python module (mirrors the htmx vendoring above).
// Only the paths we actually use are extracted; no runtime dependency.
const { default: mdi } = await import("@mdi/js");
const WANT = {
  pdf: "mdiFilePdfBox",
  img: "mdiFileImage",
  audio: "mdiFileMusic",
  video: "mdiFileVideo",
  zip: "mdiZipBox",
  txt: "mdiFileDocumentOutline",
  file: "mdiFileOutline",
  clip: "mdiPaperclip",
  lock: "mdiLock",
};
const missing = Object.entries(WANT).filter(([, k]) => typeof mdi[k] !== "string");
if (missing.length) throw new Error("missing mdi icons: " + missing.join(","));
const lines = [
  "# GENERATED by scripts/build.mjs — do not edit. Source: @mdi/js.",
  "PATHS = {",
  ...Object.entries(WANT).map(([short, k]) => `    "${short}": "${mdi[k]}",`),
  "}",
  "",
];
await writeFile("src/clanker_chat/icons.py", lines.join("\n"));
console.log("wrote src/clanker_chat/icons.py with", Object.keys(WANT).length, "icons");
